# Generated by Django 5.2.7 on 2025-10-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
